name: Create CLI Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-release:
    name: Tag Release ${{ github.head_ref }}
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: codecov/gha-workflows/.github/workflows/create-release.yml@v1.2.1
    secrets: inherit

  release:
    needs: [create-release]
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: ./.github/workflows/release_flow.yml
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    secrets: inherit